src/GolfDeptAppp/Controllers/ClubController.cs
using GolfDeptAppp.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using GolfDeptAppp.Data.Interfaces;
using GolfDeptAppp.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GolfDeptAppp.Controllers
{
    public class ClubController : Controller
    {
        
        private readonly IClubRepository _clubRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ClubController(ICategoryRepository categoryRepository, IClubRepository clubRepository)
        {
       
            _clubRepository = clubRepository;
            _categoryRepository = categoryRepository;

        }


        public ViewResult List(int categoryId)
        {
            int _categoryId = categoryId;
            IEnumerable<Club> clubs;

            string currentCategory = string.Empty;

            if (int.Equals(categoryId, 0))
            {
                clubs = _clubRepository.Clubs.OrderBy(n => n.ClubId);
                currentCategory = "All Clubs";
            }
            else
            {
                if (int.Equals(categoryId, 1))
                {
                    clubs = _clubRepository.Clubs.Where(p => p.Category.CategoryId.Equals(1)).OrderBy(p => p.Name);
                    currentCategory = "Driver";
                }
                else
                {
                    clubs = _clubRepository.Clubs.Where(p => p.Category.CategoryId.Equals(2)).OrderBy(p => p.Name);
                    currentCategory = "Putter";
                }

            }

            return View(new ClubListViewModel
            {
                Clubs = clubs,
                CurrentCategory = currentCategory
            });
        }

        public ViewResult Details(int clubId)
        {
            var club = _clubRepository.Clubs.FirstOrDefault(d => d.ClubId == clubId);
            if (club == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(club);
        }
    }
}

src/GolfDeptAppp/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GolfDeptAppp.Controllers
{
    public class ContactController : Controller
    {
        // GET: /<controller>/
        public ViewResult Index()
        {

            return View();
        }
    }
}

src/GolfDeptAppp/Controllers/ShoppingCartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using GolfDeptAppp.Data.Interfaces;
using GolfDeptAppp.Data.Models;
using GolfDeptAppp.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GolfDeptAppp.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: /<controller>/
        private readonly IClubRepository _clubRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IClubRepository clubRepository, ShoppingCart shoppingCart)
        {
            _clubRepository = clubRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int clubId)
        {
            var selectedClub = _clubRepository.Clubs.FirstOrDefault(p => p.ClubId == clubId);
            if (selectedClub != null)
            {
                _shoppingCart.AddToCart(selectedClub, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int clubId)
        {
            var selectedClub = _clubRepository.Clubs.FirstOrDefault(p => p.ClubId == clubId);
            if (selectedClub != null)
            {
                _shoppingCart.RemoveFromCart(selectedClub);
            }
            return RedirectToAction("Index");
        }

    }
    }

src/GolfDeptAppp/Views/Shared/Carousel.cshtml
<style>
.carousel-inner > .item > img, .carousel-inner > .item > a > img {
        display: block;
        height: 250px;
        min-width: 100%;
        width: 100%;
        max-width: 100%;
        line-height: 1;
    }
</style>
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="https://www.ajg.com/ImageGen.ashx?image=/media/1700008/the-ace-club_-range.png&width=1280" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="https://image.rezervasyon.com/header-img/header-golf.jpg?v=1.3.19" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="http://elitecoastalpropertygroup.com/wp-content/uploads/2017/07/Lifestyle_2.png" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

src/GolfDeptAppp/Views/Shared/ClubsSummary.cshtml
@model Club
<head>
    <script src="https://use.fontawesome.com/e1efa10af5.js"></script>
</head>

<style>
    .pic{
        height:200px;
        width:200px;
    }
    .thumbnail{
        -webkit-box-shadow: #5c5c5c 5px 5px 5px;
        -moz-box-shadow: #5c5c5c 5px 5px 5px; 
        box-shadow: #5c5c5c 5px 5px 5px;
        margin-top:10px;
        border:solid;
        border-width:1px;
    }
</style>


<div class="col-sm-4 col-lg-4 col-md-4 pull-left" style="height:475px">
    <div class="thumbnail" style="background-color:transparent url(@Model.ImageThumbnailUrl)">
        <img src="@Model.ImageThumbnailUrl" alt="" style="height:200px;width:200px;"/>
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Club" asp-action="Details" asp-route-clubId="@Model.ClubId">@Model.Name</a>
            </h3>
            @if (@Model.CategoryId == 1)
            {
                <h4>Driver</h4>
            }
            else if (@Model.CategoryId == 2)
            {
                <h4>Putter</h4>
            }
            <h3>
            @if (Model.IsPreferredClub.Equals(true))
            {
                <i class="fa fa-star" aria-hidden="true" style="color:gold"></i>
            }
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-success" id="cartButton" 
                   asp-controller="ShoppingCart" 
                   asp-action="AddToShoppingCart" 
                   asp-route-clubId="@Model.ClubId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

src/GolfDeptAppp/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

<head>
    <script src="https://use.fontawesome.com/e1efa10af5.js"></script>
</head>

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
    </ul>
}

src/GolfDeptAppp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Josefin+Sans">
        <script src="https://use.fontawesome.com/e1efa10af5.js"></script>
    <title>Golf</title>
</head>
<body style="background: radial-gradient(#808080, #e6e6e6); font-family: 'Josefin Sans', sans-serif;">
    @*@await Html.PartialAsync("Carousel")*@
    <div style="height: 250px;  min-width: 100%;  width: 100%;  max-width: 100%; display: block;">
        <img class="slide-image" src="~/Images/c1.png" alt=""style="height: 250px;  min-width: 100%;  width: 100%;  max-width: 100%; display: block;">
    </div>
    <nav class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" asp-controller ="Home" asp-action="Index">GolfDepot</a>
        <div class="container">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>*@
            </div>
            <div class="collapse navbar-collapse" id="#bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index"> Home </a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="Contact" asp-action="Index"> About Us </a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @await Component.InvokeAsync("ShoppingCartSummary")
                    @await Html.PartialAsync("LoginPartial")
                </ul>
            </div>
        </div>
    </nav>           
    <div class="container body-content" >
        @RenderBody()
        <hr/>
        <footer>
            <p><a target="_blank" href="https://github.com/etrupia"&copy; 2017 ng- ok></a></p>
        </footer>
    </div>
</body>
</html>