src/GolfDeptAppp/ViewModels/ShoppingCartViewModel.cs
using GolfDeptAppp.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GolfDeptAppp.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }
    }
}

src/GolfDeptAppp/Controllers/ClubController.cs
using GolfDeptAppp.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using GolfDeptAppp.Data.Interfaces;
using GolfDeptAppp.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GolfDeptAppp.Controllers
{
    public class ClubController : Controller
    {
        
        private readonly IClubRepository _clubRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ClubController(ICategoryRepository categoryRepository, IClubRepository clubRepository)
        {
       
            _clubRepository = clubRepository;
            _categoryRepository = categoryRepository;

        }


        public ViewResult List(int categoryId)
        {
            int _categoryId = categoryId;
            IEnumerable<Club> clubs;

            string currentCategory = string.Empty;

            if (int.Equals(categoryId, 0))
            {
                clubs = _clubRepository.Clubs.OrderBy(n => n.ClubId);
                currentCategory = "All Clubs";
            }
            else
            {
                if (int.Equals(categoryId, 1))
                {
                    clubs = _clubRepository.Clubs.Where(p => p.Category.CategoryId.Equals(1)).OrderBy(p => p.Name);
                    currentCategory = "Driver";
                }
                else
                {
                    clubs = _clubRepository.Clubs.Where(p => p.Category.CategoryId.Equals(2)).OrderBy(p => p.Name);
                    currentCategory = "Putter";
                }

            }

            return View(new ClubListViewModel
            {
                Clubs = clubs,
                CurrentCategory = currentCategory
            });
        }

        public ViewResult Details(int clubId)
        {
            var club = _clubRepository.Clubs.FirstOrDefault(d => d.ClubId == clubId);
            if (club == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(club);
        }
    }
}

src/GolfDeptAppp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using GolfDeptAppp.Data.Interfaces;
using GolfDeptAppp.Data.Models;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using GolfDeptAppp.Data;
using GolfDeptAppp.Migrations;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GolfDeptAppp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly AppDbContext _appDbContext;

        public Order localOrder;

        public OrderController(IOrderRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Checkout(Order order)
        {
            int id = 0;
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, add some clubs first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                localOrder = order;
                return RedirectToAction("CheckoutComplete");
            }

            return View(order);

        }

        [HttpGet]
        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order! :) ";
            ViewBag.CheckoutCompleteData = localOrder;
            return View();
        }
    }
}

src/GolfDeptAppp/Controllers/ShoppingCartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using GolfDeptAppp.Data.Interfaces;
using GolfDeptAppp.Data.Models;
using GolfDeptAppp.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace GolfDeptAppp.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: /<controller>/
        private readonly IClubRepository _clubRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IClubRepository clubRepository, ShoppingCart shoppingCart)
        {
            _clubRepository = clubRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int clubId)
        {
            var selectedClub = _clubRepository.Clubs.FirstOrDefault(p => p.ClubId == clubId);
            if (selectedClub != null)
            {
                _shoppingCart.AddToCart(selectedClub, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int clubId)
        {
            var selectedClub = _clubRepository.Clubs.FirstOrDefault(p => p.ClubId == clubId);
            if (selectedClub != null)
            {
                _shoppingCart.RemoveFromCart(selectedClub);
            }
            return RedirectToAction("Index");
        }

    }
    }

src/GolfDeptAppp/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

<div class="row checkoutForm">
    <h2>Your shopping cart</h2>
    <h4>Here are the clubs in your shopping cart.</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Club</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Club.Name</td>
                    <td class="text-right">@line.Club.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Club.Price).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-clubId="@line.Club.ClubId"></a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.ShoppingCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Check out</a>
            <a class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Add more clubs<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Club" asp-action="List" asp-route-categoryId= "1">Drivers</a></li>
                    <li><a asp-controller="Club" asp-action="List" asp-route-categoryId= "2">Putters</a></li>
                    <li class="divider"></li>
                    <li><a asp-controller="Club" asp-action="List" asp-route-categoryId= "0">All Clubs</a></li>
                </ul>
            </a>
        </div>
    </div>
</div>